name: Deploy to GitHub Pages

# Kịch bản này sẽ tự động chạy mỗi khi bạn push code lên nhánh "main"
on:
  push:
    branches: ["main"] # Nếu nhánh chính của bạn tên là "master", hãy đổi thành "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tạo file config.js
        run: |
          echo "${{ secrets.PROD_CONFIG }}" > config.js

      - name: Deploy lên GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . 